# Accepts the LTI Tool Consumer Launch Request
name: receive-cengage-launch-request
run-name: Cengage Launch Request
# trigger the workflow from the Cengage launch request
on:
  repository_dispatch:
jobs:
  accept-lti-launch-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout student's main
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TEST_FILES_AUTH }}

      # Parse launch request
      - name: Write payload to a file
        run: |
          touch payload.json
          echo '${{ toJSON(github.event.client_payload.data) }}' > payload.json

      - name: Save LTI launch payload as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact-${{ github.event.client_payload.data.context_id }}-payload
          path: |
            ./payload.json
          retention-days: 1

      #- name: Save launch data as env variables
      #  uses: actions/checkout@v3
      #  with: 
      #    repo-token: ${{ secrets.TEST_FILES_AUTH }}
      #  env:
      #    SOURCE_ID: ${{ toJSON(github.event.client_payload.data.lis_result_sourcedid) }}
      #    USER_ID: ${{ toJSON(github.event.client_payload.data.user_id) }}
      #    LIS_OUTCOME_SERVICE_URL: ${{ toJSON(github.event.client_payload.data.lis_outcome_service_url) }}

      - name: List repo variables
        run: |
          variables=$(curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.TEST_FILES_AUTH }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/cengage-ide-content/9780357880876_pld-10e-cpp/actions/variables)
          echo "$variables"
        
      - name: Create LTI repo variables
        run: |
          if [ -z "${{vars.LIS_OUTCOME_SERVICE_URL}}"]; then
            curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TEST_FILES_AUTH }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/cengage-ide-content/9780357880876_pld-10e-cpp/actions/variables \
            -d '{"name":"SOURCE_ID","value":"${{github.event.client_payload.data.lis_result_sourceid}}"}'
            
            curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TEST_FILES_AUTH }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/cengage-ide-content/9780357880876_pld-10e-cpp/actions/variables \
            -d '{"name":"USER_ID","value":"${{ github.event.client_payload.data.user_id}}"}'
            
            curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TEST_FILES_AUTH }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/cengage-ide-content/9780357880876_pld-10e-cpp/actions/variables \
            -d '{"name":"LIS_OUTCOME_SERVICE_URL","value":"${{github.event.client_payload.data.lis_outcome_service_url}}"}'
          fi

      - name: Update LTI repo variables
        run: |
          if [ ! -z "${{vars.LIS_OUTCOME_SERVICE_URL}}" ]; then
            curl \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TEST_FILES_AUTH }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/cengage-ide-content/9780357880876_pld-10e-cpp/actions/variables/SOURCE_ID \
            -d '{"name":"SOURCE_ID","value":"${{github.event.client_payload.data.lis_result_sourceid}}"}'
            
            curl \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TEST_FILES_AUTH }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/cengage-ide-content/9780357880876_pld-10e-cpp/actions/variables/USER_ID \
            -d '{"name":"USER_ID","value":"${{github.event.client_payload.data.user_id}}"}'
            
            curl \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TEST_FILES_AUTH }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/cengage-ide-content/9780357880876_pld-10e-cpp/actions/variables/LIS_OUTCOME_SERVICE_URL \
            -d '{"name":"LIS_OUTCOME_SERVICE_URL","value":"${{github.event.client_payload.data.lis_outcome_service_url}}"}'
          fi
